
FROM node:alpine AS builder

ARG VERSION="1.0.0"

WORKDIR /usr/app

COPY package.json .
COPY index.js .

RUN npm install

ENV APP_VERSION=${VERSION}

FROM nginx:alpine

WORKDIR /usr/share/nginx/html

COPY --from=builder /usr/app/index.js /usr/share/nginx/html/index.js
COPY --from=builder /usr/app/package.json /usr/share/nginx/html/package.json

COPY nginx.conf /etc/nginx/nginx.conf

HEALTHCHECK --interval=10s --timeout=3s --retries=3 \
  CMD curl -f http://localhost || exit 1

CMD ["nginx", "-g", "daemon off;"]
